// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejvoewlkfpgdauytrit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lanZvZXdsa2ZwZ2RhdXl0cml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODE4NDcsImV4cCI6MjA3MDI1Nzg0N30.x6y2XMoVKeO7SYZLarDbXHvmTkCFB7-z_ftSe9vGkS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});